### PR TITLE
Lightsaber: Add Shebang

### PR DESCRIPTION
**Pull request by Neo-Oli**
`read -p` works differently in zsh, which makes the script fail if a user has zsh instead of bash

### CODE REVIEW

**Comment by josuah** [comment]
Hello.  I used `read -r`, which is a quite [standard](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/read.html) way to use read, but I agree the use of a shebang is a good idea.

I avoided it as scripts are POSIX (i.e. run on any shell), and if no shebang is specified, the current default shell is used (bash, zsh, mksh...).  It did work with zsh when I tried.  '_'

 I was needing it for termux in android, as android does not have `/bin` directory (I had to run `su; mount -o remount,rw /; ln -s /system/bin /bin`).

But I do not want to encourage systems to use a different location for `/bin`, so I will add shebang everywhere.

By the way, I saw you are very good at using termux.  :)

**Comment by Neo-Oli** [comment]
Ah yeah, sorry. When running the script it gets executed with `sh` not the current shell. On most systems `sh` is a symlink for `bash` (running in --posix mode). But on a systems that have dash for `sh` (like termux) `read -r` doeasn't work. 
```
~ $ sh
$ read -r
sh: 2: read: arg count
```
It's because sh requires a variable for the reply. 
`read -r REPLY`

**Comment by josuah** [comment]
Oh yes, indeed.  Thanks.

I still prefer to use POSIX shell, so I will add a variable name.  I learned something today.

**Comment by Neo-Oli** [comment]
Yeah, if you add the variable name you don't need the shebang (which would work better for termux).
To deal with the shebangs on termux, I keep my bin folder somewhere else (where all the shebangs are normal like `#!/bin/bash`. That's where I make all the changes. I then copy the bin folder to ~/bin and run `find ~/bin/* -type f | xargs termux-fix-shebang` which fixes the shebang to the proper termux shebangs like `#!/data/data/com.termux/files/usr/bin/bash`.

**Pull request closed without merging**
